name: Generate Widoco Documentation

on:
  push:
    branches:
      - main  # Run the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository to get the .ttl file and Widoco-Conf
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment (Widoco requires Java)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Step 3: Download Widoco
      - name: Download Widoco
        run: |
          wget https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-17.jar -O widoco.jar

      # Step 4: Generate HTML documentation using the Widoco-Conf file
      - name: Generate HTML documentation
        run: |
          ont_file="TransportationMeans.ttl"  # Replace with your actual ontology filename
          conf_file="Widoco-Conf"  # Path to your Widoco-Conf file
          output_folder="Website-Ontology"

          # Ensure the Widoco-Conf file exists
          if [ ! -f "$conf_file" ]; then
            echo "Widoco-Conf file not found: $conf_file"
            exit 1
          fi

          # Run Widoco with the conf file
          java -jar widoco.jar -ontFile "$ont_file" -outFolder "$output_folder" \
          -confFile "$conf_file" -rewriteAll -webVowl -oops -includeIndividuals \
          -includeImportedOntologies -htaccess -displayOntologySerializations -uniteSections -createFolder

      # Step 5: Verify the files generated by Widoco
      - name: List generated files
        run: |
          echo "Listing files in $output_folder"
          ls -R "$output_folder"
