name: Generate Widoco Documentation

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Widoco requires Java, usually version 11 or later

      - name: Download Widoco (latest release)
        run: |
          wget https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-17.jar
          mv widoco-1.4.25-jar-with-dependencies_JDK-17.jar widoco.jar 

      - name: Generate HTML documentation using Widoco
        run: |
          java -jar widoco.jar -ontFile Test2/TransportationMeans.ttl -outFolder docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT3 }}
          publish_dir: ./docs  # The folder where Widoco output is stored